Add Interfaces-PHP
DanielHe4rt/php4noobs pull request #100
Opened 2022-09-29 16:36 UTC by Lucasm4sco

2023-01-08 17:13 UTC, DanielHe4rt requested changes
Achei que o conteúdo está indo pra um bom caminho, mas falta um pouco mais de contextos reais pra galera não ficar perdida.

Fora os padrões de código, já que como é educativo seria legal ensinarmos a usar do jeito certo.

Depois de implementar isso ai, me dá um salve que eu reviso dnv <3

2023-01-08 17:13 UTC, DanielHe4rt commented on 4-Intermediário/8-Interfaces.md
> +  interface nome_interface
Acho que pra um melhor entendimento seria legal já de cara colocar exemplos práticos pra essa parte de interfaces. Podendo ser: 
- Comandos
- Provedores
- Factories etc etc

... e também quando for escrever código de exemplo, tente seguir a (PSR-12)[https://www.php-fig.org/psr/psr-12/] e colocar nome classes em **PascalCase**. 

```suggestion
  interface ProvedorPagamentoInterface
```

2023-01-08 17:13 UTC, DanielHe4rt commented on 4-Intermediário/8-Interfaces.md
> +  class nome_classe implements nome_interface
A mesma coisa da PSR-12.

2023-01-08 17:13 UTC, DanielHe4rt commented on 4-Intermediário/8-Interfaces.md
> +	    public function helloWorld();
Lembrar que métodos de uma interface também podem garantir o tipo de retorno do dado. Além da assinatura dos nome da função e seus parametros, o retorno também é imprescindível nessas situações.
```suggestion
	    public function helloWorld(): void
```

2023-01-08 17:13 UTC, DanielHe4rt commented on 4-Intermediário/8-Interfaces.md
> +O código acima terá o output: ```Valor em Exemplo - Valor em Exemplo```.
Não sei se você conhece, mas falar sobre o (Open Closed Principle)[https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle] é bem válido quando falamos de Interfaces.

2023-01-08 21:14 UTC, Lucasm4sco commented
Beleza (: irei dar uma olhada melhor nestes conceitos e assim que eu implementar mando pra ti.

2023-06-11 18:13 UTC, DanielHe4rt commented on 4-Intermediário/8-Interfaces.md
> +  class nome_classe implements nome_interface
```suggestion
  class PaypalProvider implements PaymentProvider
```

2023-06-11 18:14 UTC, merged